---
output:
  md_document:
    variant: markdown_github
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, echo = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "README-"
)
```

# ReadMe for the IncucyteDRC package

The IncucyteDRC package provides functionality for the analysis of data from live cell imaging cell proliferation experiments carried out on the Essen Biosciences IncuCyte ZOOM instrument

It is described in a paper by [Chapman et al 2016](http://f1000research.com/articles/5-962/) in F1000Research.  There are two vignettes describing the package that can be viewed by typing `browseVignettes('IncucyteDRC')` once the package is installed and loaded or by clicking on the links below:  
[Overview of IncucyteDRC](https://cran.r-project.org/web/packages/IncucyteDRC/vignettes/Overview.html)  
[Exporting from IncucyteDRC](https://cran.r-project.org/web/packages/IncucyteDRC/vignettes/IncucyteZoomExport.html)  

The production version can be found on CRAN:  
https://cran.r-project.org/web/packages/IncucyteDRC/

Whereas the development version is on GitHub:  
https://github.com/chapmandu2/IncucyteDRC

Further information on installation and common issues can be found on the git repo wiki:  
https://github.com/chapmandu2/IncucyteDRC/wiki/Installation-Issues

There is a hosted version of the shiny app to try out the package without installing it:  
https://cruk-mi-ddu.shinyapps.io/IncucyteDRC_app2/

Example data can be found in the git repo at:  
https://github.com/chapmandu2/IncucyteDRC/tree/master/inst/extdata

If you find any bugs or have any feature suggestions please submit an issue on GitHub:  
https://github.com/chapmandu2/IncucyteDRC/issues
