#' importIncucyteData
#'
#' Imports data exported from Incucyte Zoom software. Handles both old and new format data files.
#'
#' @param filepath Path to a data file generated by the Incucyte Zoom software
#' @param metric Metric must be either pc (percent confluence) or ca (confluence area). Default is pc.
#' @param plateid An identifier for the plate. If set to NULL then filename used as default
#'
#' @importFrom utils head read.table write.table
#' @return IncucyteDRCPlateData object
#' @export
importIncucyteData <- function(filepath, metric='pc', plateid=basename(filepath)) {
    message(sprintf("Getting %s data for plate %s from:\n%s", metric, plateid, filepath))

    #check that the metric type is valid
    if (!(metric %in% c('pc','ca'))) 
        stop('metric must be either pc (percent confluence) or ca (confluence area)')

    # Read in the file as lines to examine structure
    lines <- readLines(filepath)
    
    # Function to find the data start row
    find_data_start <- function(lines) {
        # Look for either Date Time or Elapsed in header
        date_rows <- grep("^Date.Time|^Date Time", lines, perl=TRUE)
        if (length(date_rows) == 0) {
            stop('Could not find data header. Please check input file format')
        }
        return(date_rows[1])
    }
    
    # Get the starting row of data
    start_row <- find_data_start(lines)
    
    # Read the data with appropriate handling for both formats
    data_df <- try({
        # First try reading with tab separator
        df <- read.table(filepath, header=TRUE, sep='\t', skip=start_row-1, 
                        stringsAsFactors=FALSE, check.names=FALSE)
        
        # Identify the time columns
        time_cols <- grep("^Date.Time$|^Date Time$|Elapsed", names(df), value=TRUE)
        
        # Extract elapsed time and reshape the data
        elapsed_data <- df[,"Elapsed"]
        
        # Remove the time columns
        df <- df[,!names(df) %in% time_cols]
        
        # Convert to long format
        result <- tidyr::gather(data.frame(elapsed=elapsed_data, df), 
                              wellid, value, -elapsed)
        
        # Clean up well IDs for new format - extract just the well identifier if needed
        if (any(grepl(",", result$wellid))) {
            # For new format, take everything before the first comma or space
            result$wellid <- gsub("^([^, ]+).*", "\\1", result$wellid)
        }
        
        result
    })
    
    if (inherits(data_df, "try-error")) {
        stop("Failed to parse data file. Please check format.")
    }

    # Create output object
    output <- list(
        data = as.data.frame(data_df),
        metric = metric,
        plateid = plateid
    )
    
    class(output) <- 'IncucyteDRCPlateData'
    return(output)
}
