#' importIncucyteData
#'
#' Imports data exported from Incucyte Zoom software. Handles both old and new format data files.
#'
#' @param filepath Path to a data file generated by the Incucyte Zoom software
#' @param metric Metric must be either pc (percent confluence) or ca (confluence area). Default is pc.
#' @param plateid An identifier for the plate. If set to NULL then filename used as default
#'
#' @importFrom utils head read.table write.table
#' @return IncucyteDRCPlateData object
#' @export
importIncucyteData <- function(filepath, metric='pc', plateid=basename(filepath)) {
    message(sprintf("Getting %s data for plate %s from:\n%s", metric, plateid, filepath))

    if (!(metric %in% c('pc','ca'))) 
        stop('metric must be either pc (percent confluence) or ca (confluence area)')

    # Read all lines
    lines <- readLines(filepath)
    
    # Find data start - look for Elapsed header
    start_row <- grep("^Date.Time|^Date Time|Elapsed", lines, perl=TRUE)[1]
    if (is.na(start_row)) stop("Could not find data header")
    
    # Read data
    df <- read.table(filepath, header=TRUE, sep='\t', skip=start_row-1, 
                    stringsAsFactors=FALSE, check.names=FALSE,
                    colClasses='character') # Read all as character first
    
    # Extract and convert elapsed time 
    elapsed_col <- grep("Elapsed", names(df), value=TRUE)
    elapsed_data <- as.numeric(df[[elapsed_col]])
    
    # Remove time columns
    time_cols <- grep("^Date.Time$|^Date Time$|Elapsed", names(df))
    df <- df[,-time_cols, drop=FALSE]
    
    # Gather to long format
    result <- tidyr::gather(data.frame(elapsed=elapsed_data, df), 
                          wellid, value, -elapsed)
    
    # Clean well IDs and convert values to numeric
    result$wellid <- gsub("^([^, ]+).*", "\\1", result$wellid)
    result$value <- as.numeric(result$value)
    
    # Remove any NA rows
    result <- result[!is.na(result$elapsed) & !is.na(result$value),]
    
    # Ensure we have data
    if (nrow(result) == 0) stop("No valid data found after processing")
    
    output <- list(
        data = as.data.frame(result),
        metric = metric,
        plateid = plateid
    )
    
    class(output) <- 'IncucyteDRCPlateData'
    return(output)
}
