#' splitIncucyteDRCPlateData
#'
#' Function to construct a list of IncucyteDRCSet objects from a IncucyteDRCPlateData object.
#'
#' @param platemap Platemap dataframe of the form generated by importPlatemapXML
#' @param platedata IncucyteDRCPlateData object to be split
#' @param group_columns Vector of columns that are present in the data frame to generate the groups.
#' @param cut_time The time at which to extract the data for the dose response curve.  Default is NULL.
#'
#' @return list of IncucyteDRCSet objects
#' @export
#'
#' @examples
#' test_pm <- importPlatemapXML(system.file(file='extdata/example.PlateMap', package='IncucyteDRC'))
#' test_data <- importIncucyteData(system.file(file='extdata/example_data.txt', package='IncucyteDRC'), metric='pc')
#'
#' test_list <- splitIncucyteDRCPlateData(test_pm, test_data, group_columns='growthcondition')
#'
#' str(test_list)


splitIncucyteDRCPlateData <- function(platemap, platedata, group_columns, cut_time=NULL) {

    stopifnot(class(platedata) == 'IncucyteDRCPlateData')
    stopifnot(group_columns %in% colnames(platemap))

    #get rid of blanks
    platemap <- platemap %>% dplyr::filter(samptype %in% c('C', 'S'))

    #generate group ids using group_columns
    platemap <-  platemap %>%  dplyr::mutate(group_idx = dplyr::group_indices_(platemap, .dots=group_columns) )

    #split platemap based on group_idx
    platemap_list <- split(platemap, platemap$group_idx)

    #lapply makeIncucyteData across list of platemaps
    outdata <- lapply(platemap_list, function(x) makeIncucyteDRCSet(platemap = x, platedata = platedata, cut_time = NULL))

    class(outdata) <- 'IncucyteDRCSetList'

    return(outdata)

}
